Updated Topic and StreamId parameters without MetricName
osisoft/PI-Adapter-MQTT-Docs pull request #16
Opened 2021-06-08 15:51 UTC by TinaUll

2021-06-08 17:14 UTC, arcini requested changes
The MQTT topic string must still contain the messagetype as the third parameter per the mqtt specification, but we now generate the default stream id without the message type. So, the topic should still be provided with the {messageType}. While we support {Topic}.{MetricName} as a DefaultStreamIdPattern, this would have to be manually configured in the data source configuration, and technically we support any combination of the three parameters and added strings. So really we just continue to have the Topic as a parameter that can be used in a custom DefaultStreamIdPattern, but any streamid pattern is technically supported.

Also, there should be an update in the Data Source (Sparkplug B) page for the defaultStreamIdPattern item. We now support a third parameter, {BaseTopic}, and the default pattern is now {BaseTopic}.{MetricName}

2021-06-08 23:03 UTC, arcini requested changes

2021-06-08 23:03 UTC, arcini commented on content/configuration/data-selection-sparkplug-b.md
> +| **Topic** | Required | `string` | The MQTT topic string in the following format: `{namespace}/{groupId}/{messageType}/{edgeNodeId}/{deviceId}` or the MQTT base topic string in the following format:
After further reviewing the code, I am confident that the full topic string must be supplied by the user for the Topic field during configuration. I would move the base topic string explanation to the DefaultStreamIdPattern documentation, since if a user supplies the basetopic themselves in place of the topic field, it would break the program

2021-06-08 23:03 UTC, arcini commented on content/configuration/data-selection-sparkplug-b.md
> +| **Topic** | Required | `string` | The MQTT topic string in the following format: `{namespace}/{groupId}/{messageType}/{edgeNodeId}/{deviceId}` or the MQTT base topic string in the following format:
Otherwise looks good!

2021-06-09 23:26 UTC, TinaUll commented
@arcini One hopefully last look, please. (Feel free to suggest edits directly!)

2021-06-10 15:49 UTC, merged