Create client-settings.md
osisoft/PI-Adapter-MQTT-Docs pull request #17
Opened 2021-06-11 22:30 UTC by TinaUll

Hi @rgralakosi, I drafted the MQTT client settings configuration topic. Please take a look (especially the parameter descriptions; default values are missing!) and let me know if this works. Thank you and Happy Friday!

2021-06-11 23:41 UTC, rgralakosi requested changes

2021-06-11 23:41 UTC, rgralakosi commented on content/configuration/client-settings.md
> +| **MaxInternalQueueSize**      | Optional | `integer` | Maximum number of items that can be in the adapter internal queue. <br><br>Allowed value: >= `250`<br>Default value: `` |
Zdenek changed the parameter name from **MaxInternalQueueSize** to **MaxClientQueueSize** :-)

2021-06-11 23:41 UTC, rgralakosi commented on content/configuration/client-settings.md
> +    "maxInternalQueueSize": 1000
As mentioned above, this has been changed to **maxClientQueueSize**!

2021-06-11 23:41 UTC, rgralakosi commented on content/configuration/client-settings.md
> +| **MaxInternalQueueSize**      | Optional | `integer` | Maximum number of items that can be in the adapter internal queue. <br><br>Allowed value: >= `250`<br>Default value: `` |
The default value for MaxClientQueueSize is 1000.

2021-06-11 23:41 UTC, rgralakosi commented on content/configuration/client-settings.md
> +| **QosLevel** | Optional |  `integer`<br><br>or<br><br>`enum`              | Defines the guarantee of delivery for a specific item.<br><br> Allowed value:<br>`0` or `AtMostOnce`: There is no guarant
The default value for QosLevel is 2 ("ExactlyOnce")

2021-06-11 23:41 UTC, rgralakosi commented on content/configuration/client-settings.md
> +| **KeepAlivePeriod** | Optional | `string`<br>(timespan)          | The maximum time that can elapse between sending two data items. <br><br> Allowed value: >= `0:00:05` (5 seconds)<br>Default value
The default value for KeepAlivePeriod is "00:00:30" (30 seconds).

2021-06-12 00:04 UTC, TinaUll commented
Thanks, @rgralakosi. Topic is updated. Let me know if you approve now :)

2021-06-14 21:34 UTC, merged