updated release notes
osisoft/PI-Adapter-MQTT-Docs pull request #33
Opened 2021-09-24 16:32 UTC by kshuOSIsoft

Updated release notes

2021-09-24 17:03 UTC, TinaUll commented on content/release-notes/release-notes.md
```suggestion
PI Adapter for MQTT 1.0
Adapter framework 1.4
```

2021-09-24 17:07 UTC, TinaUll commented on content/release-notes/release-notes.md
> +## Known issues
```suggestion
### Known issues
```

2021-09-24 17:07 UTC, TinaUll commented on content/release-notes/release-notes.md
> +## System requirements
```suggestion
### System requirements
```

2021-09-24 17:08 UTC, TinaUll commented on content/release-notes/release-notes.md
> +## Installation
```suggestion
### Installation and upgrade
```

2021-09-24 17:08 UTC, TinaUll commented on content/release-notes/release-notes.md
> +## Uninstallation
```suggestion
### Uninstallation
```

2021-09-24 17:10 UTC, TinaUll requested changes
@kshuOSIsoft, which template did you use for the release notes? Looks like a lot of the formatting has been reverted in your PR.

2021-09-24 17:14 UTC, TinaUll commented on content/release-notes/release-notes.md
> +This section is intended to provide relevant security-related information to guide your installation or upgrade decision. OSIsoft is proactively disclosing aggregate information about the number and
@kshuOSIsoft This section is intended to list any supporting documentation or reference documentation (like EdgeCmd), it's not intended for security related information.

2021-09-24 17:14 UTC, kshuOSIsoft commented
> 
> 
> @kshuOSIsoft, which template did you use for the release notes? Looks like a lot of the formatting has been reverted in your PR.

I copied it from https://github.com/osisoft/PI-Adapter-OPC-UA-Docs/blob/v1.2/content/release-notes/release-notes.md

2021-09-24 17:37 UTC, kshuOSIsoft commented
Actually I don't know what happened, let me redo the release notes real quick.

2021-09-30 17:40 UTC, zryska approved these changes

2021-09-30 17:42 UTC, merged